name: CI and Release
on:
  merge_group:
  push:
    branches:
      - main
    # Trigger on version tags
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  # Dockerfile Linting
  hadolint:
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_lint.yml@v0.2.8 # yamllint disable-line rule:line-length
    with:
      dockerfile: Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: celestiaorg/.github/.github/actions/yamllint@v0.2.8

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install -g markdownlint-cli@0.32.1
          markdownlint --config .markdownlint.yaml '**/*.md'

  go-ci:
    uses: ./.github/workflows/go-ci.yml

  # If this was a workflow dispatch event, we need to generate and push a tag
  # for goreleaser to grab
  version_bump:
    needs: [hadolint, yamllint, markdown-lint, go-ci]
    runs-on: ubuntu-latest
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        # Placing the if condition here is a workaround for needing to block
        # on this step during workflow dispatch events but the step not
        # needing to run on tags. If we had the if condition on the full
        # version_bump section, it would skip and not run, which would result
        # in goreleaser not running either.
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: mathieudutour/github-tag-action@v6.1

      - name: Version Release
        uses: celestiaorg/.github/.github/actions/version-release@v0.2.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.version }}

  # Generate the release with goreleaser to include pre-built binaries
  goreleaser:
    needs: version_bump
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && contains(github.ref, 'refs/tags/'))
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      # Generate the binaries and release
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TODO: permission issue, but not worth fixing as this should be refactored
  # into the celestiaorg/.github repo, at which point any permission issues will
  # be resolved.
  #
  # docker:
  #   needs: [release]
  #   uses: ./.github/workflows/docker-build.yml
